server:
  port: 8080
wx:
  uniapp:
    appid: wxd24ab768b910ae57
    secret: 50f7f07419e8fdb360cf80a010cb11fb
sa-token:
  token-name: satoken
  timeout: 2592000
  token-style: uuid
  is-concurrent: false
  is-share: false
  is-log: true
  active-timeout: -1
  is-print: true

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://119.91.238.231:3306/wf_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v3
    mcp:
      client:
        enabled: true
        type: SYNC
        request-timeout: 120s
        sse:
          connections:
            zuimei-weather:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/zuimei-getweather/sse
              headers:
                Authorization: Bearer ${DASHSCOPE_API_KEY}
  application:
    name: weather-forecast
  data:
    redis:
      host: 119.91.238.231
      port: 6379
      password: 123456
      database: 0
      timeout: 200000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 0
          max-wait: 100000ms
  mail:
    host: smtp.qq.com
    port: 587
    username: 2472613445@qq.com
    password: jccsjzzqzdcwdiga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
milvus:
  uri: https://in03-50c4bee8142f395.serverless.aws-eu-central-1.cloud.zilliz.com
  token: 8e30a9720b997d189fd5b12a26c07ef5f2e6269da94bd4db40bcfa9bbdc2874bedd0c2e0cd167566ec44e484f4264894ca109a6d
  collection:
    name: wf_general_acknowledge
    dimension: 1024
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

aliyun:
  sms:
    accessKeyId: your-access-key-id
    accessKeySecret: your-access-key-secret
    signName: your-sign-name
    templateCode: your-template-code

mcp:
  weather:
    endpoint: https://dashscope.aliyuncs.com/api/v1/mcps/zuimei-getweather/sse
    api-key: ${DASHSCOPE_API_KEY}
    base-url: https://dashscope.aliyuncs.com
    sse-path: /api/v1/mcps/zuimei-getweather/sse

