wx:
  uniapp:
    appid: wxd24ab768b910ae57
    secret: 50f7f07419e8fdb360cf80a010cb11fb
sa-token:
  token-name: satoken
  timeout: 2592000
  token-style: uuid
  is-concurrent: false
  is-share: false
  is-log: true
  active-timeout: -1

spring:
  datasource:
    url: jdbc:mysql://119.91.238.231:3306/wf_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
  application:
    name: weather-forecast
milvus:
  uri: https://in03-50c4bee8142f395.serverless.aws-eu-central-1.cloud.zilliz.com
  token: 8e30a9720b997d189fd5b12a26c07ef5f2e6269da94bd4db40bcfa9bbdc2874bedd0c2e0cd167566ec44e484f4264894ca109a6d
  collection:
    name: wf_general_acknowledge
    dimension: 1024
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
server:
  port: 8080
