server:
  port: 8080
wx:
  uniapp:
    appid: 
    secret: 
sa-token:
  token-name: satoken
  timeout: 2592000
  token-style: uuid
  is-concurrent: false
  is-share: false
  is-log: true
  active-timeout: -1

spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
  ai:
    dashscope:
      api-key: 
  application:
    name:
  data:
    redis:
      host: 119.91.238.231
      port: 6379
      password: 123456
      database: 0
      timeout: 
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 0
          max-wait: 
  mail:
    host: 
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
milvus:
  uri: 
  token: 
  collection:
    name: 
    dimension: 1024
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

aliyun:
  sms:
    accessKeyId: your-access-key-id
    accessKeySecret: your-access-key-secret
    signName: your-sign-name
    templateCode: your-template-code

