-- 聊天记录表（用于AI对话记忆存储）
CREATE TABLE CHAT_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID，从100000开始',

    -- 关联信息
    SESSION_ID BIGINT NOT NULL COMMENT '会话ID，关联CHAT_SESSION.ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID，关联USER_INFO.ID',

    -- 消息内容
    ROLE VARCHAR(20) NOT NULL COMMENT '消息角色：user=用户，assistant=AI助手，system=系统',
    CONTENT TEXT NOT NULL COMMENT '消息内容文本',
    MESSAGE_TYPE VARCHAR(20) DEFAULT 'text' COMMENT '消息类型：text=文本，image=图片，tool=工具调用',

    -- 工具调用结果（如果是工具消息）
    TOOL_RESULT TEXT NULL COMMENT '关联的工具调用结果（JSON格式）',

    -- 消息序号（用于排序）
    SEQUENCE INT NOT NULL COMMENT '消息在会话中的序号',

    -- 状态与时间
    AVAILABLE TINYINT(1) DEFAULT 1 COMMENT '是否可用：1=可用，0=不可用',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '消息创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '消息更新时间',

    -- 索引优化
    INDEX IDX_SESSION_ID (SESSION_ID),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_ROLE (ROLE),
    INDEX IDX_SEQUENCE (SEQUENCE),
    INDEX IDX_AVAILABLE (SESSION_ID, AVAILABLE),
    INDEX IDX_CREATE_TIME (CREATE_TIME)

) ENGINE=InnoDB
  AUTO_INCREMENT = 100000
  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='AI对话聊天记录表';
